[features]
seeds = false
skip-lint = false

[programs.localnet]
xxx = "your_program_id_here"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node scripts/*.ts"

[toolchain]
anchor_version = "0.29.0"
